### PR TITLE
extend functionality to handle lists of geometries

### PR DESCRIPTION
**Pull request by edzer**

### CODE REVIEW

**Comment by rubak** [comment]
Thanks for these changes. I'm trying to figure out why it doesn't pass on travis and appveyor. The compilation ends with a mysterious

    make: *** No rule to make target `geometry/s2loop.o', needed by `s2.dll'.  Stop.

It runs happily through the list of files in src/Makevars until `geometry/s2latlngrect.o` and then it fails for `s2loop.o`. I don't see anything special about `s2loop.cc`/`s2loop.o`. Do you know what is going on? I'm running it on R-hub now too see if the problem persists there.

**Comment by edzer** [comment]
For some reason, `s2loop.cc` was not included when building a source pkg - no clue why.

**Comment by edzer** [comment]
Thanks!

**Comment by rubak** [comment]
Well thanks for putting in the work. In the bigger picture it would be good to discuss what functions we need to implement and how to structure the objects in `s2`. Should we open an issue here or in r-spatial/sf to discuss which functions could be useful and how we get things rolling?

**Comment by edzer** [comment]
Great idea, there are more people there. There's also the option to move s2 to the r-spatial organisation, and make you a member of that. Shall I start the issue?

**Comment by rubak** [comment]
Sure, go ahead and open an issue. Then I will close this and we can continue the discussion there.

**Comment by rubak** [comment]
Well, actually I don't see anywhere I can close this. Maybe because it is your pull request and not an issue. Anyway let's continue the discussion of useful features for sf over there...

**Comment by edzer** [comment]
By merging it it automatically closed (number of PRs is now 0).

**Comment by edzer** [comment]
https://github.com/r-spatial/sf/issues/502

**Pull request merged**
